sonar.projectKey=nosipholusanda692-create_globalpay-portal
sonar.projectName=GlobalPay International Payments Portal
sonar.organization=nosipholusanda692-create
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/build/**,**/*.test.js,**/coverage/**
sonar.sourceEncoding=UTF-8